### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Yetam/CGP#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by Yetam** [comment]
Hey :) In /library dir I added the CGPlib.h under GNU license. Feel free to use and ask. I am trying my best to add the version with implementation to cellular automata (which is my master thesis) but firstly i have to clean it up - the same as i did with library now

**Comment by suprafun** [comment]
Thank you very much.
